<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ1VZXMf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ1VZXMf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ1VZXMf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ1VZXMf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ1VZXMf\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z1VZXMf',
    'container.build_id' => '41fd025e',
    'container.build_time' => 1791294465,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ1VZXMf');
